### ISSUE TITLE
strange build / linker error for petsc 3.7.6 on fedora 29 / gcc 8.3

### ISSUE THREAD

**Issue by koecher** [dealii/candi#112]
just encountered a build / linker error for petsc 3.7.6 on fedora 29 / gcc 8.3

- in the lib folder I have a couple of static libraries, which I don't understand - those should be dynamical ones
- got serval gcc errors, that a `*.dylib ` is not found for linux-2 platform

I will have a look into that soonly and patch if possible.

**Comment by krishnakumarg1984** [comment]
@koecher 

I too get identical errors reported by you. 

>
>OS: Ubuntu 18.04.3 LTS x86_64
>Host: Precision Tower 3620
>Kernel: 4.19.65-041965-generic 

Can you please look into this and help with a fix?

**Comment by koecher** [comment]
Thanks for reporting. I’m in vacation currently. I will consider it by the end of this month. 
If anyone else have a patch already, please let me know...
