### ISSUE TITLE
trilinos md5sum changed

### ISSUE THREAD

**Issue by tjhei** [dealii/candi#125]
I checked the log in https://github.com/koecher/candi/issues/83 and it looks like something is messed up:
download from https://tjhei.info/candi-mirror/trilinos-release-12-10-1.tar.gz 40f28628b63310f9bd17c26d9ebe32b1
download from https://github.com/trilinos/Trilinos/archive/trilinos-release-12-10-1.tar.gz 667333dbd7c0f031d47d7c5511fd0810
in our package: 40f28628b63310f9bd17c26d9ebe32b1

It looks like they changed their tarballs in some way.

@koecher do you have a suggestion on what to do? (we should bump to a more recent release, but that doesn't fix the older candi release for 9.1)

**Comment by koecher** [comment]
curious.

I believe it is better if we change the tarball on your server to the current version and update the checksum for the branches dealii-8.5, dealii-9.0, dealii-9.1 and master.

Then, in a second step, we should update the trilinos package (I was asked for this last week in Hannover and hope that there will be a pull request soonly.

**Comment by tjhei** [comment]
> hope that there will be a pull request soonly.

you mean #92 ? I should update to the latest version...

> I believe it is better if we change the tarball on your server to the current version and update the checksum for the branches dealii-8.5, dealii-9.0, dealii-9.1 and master.

The problem is that any current checkout of candi will fail the moment I change the file on the server. We could try changing the filename and keep both files around?

**Comment by koecher** [comment]
> > hope that there will be a pull request soonly.
> 
> you mean #92 ? I should update to the latest version...

Oh, this was so long ago - I forgot the issues we had there.

> > I believe it is better if we change the tarball on your server to the current version and update the checksum for the branches dealii-8.5, dealii-9.0, dealii-9.1 and master.
> 
> The problem is that any current checkout of candi will fail the moment I change the file on the server. We could try changing the filename and keep both files around?

The problem is, that the natural source has now a new checksum. Maybe we should add the opportunity to give more than one checksum. Then we could keep the old tarball on the server and update the trilinos package file. What do you think on that?

**Comment by tjhei** [comment]
something like #127 ?

**Comment by tjhei** [comment]
this is now fixed on master, 9.1, 9.0, and 8.5.
