### ISSUE TITLE
testing for 9.2

### ISSUE THREAD

**Issue by tjhei** [dealii/candi#143]
I created the branch https://github.com/dealii/candi/tree/dealii-9.2 and I think it is ready to go but I would appreciated some testing before I make this the default.

**Comment by egretscitech** [comment]
Hi Timo
I followed the steps in candi.sh instruction while installing dealii on macos. An Error says" 
ld: library not found for -lgfortran clang: error: linker command failed with exit code 1" during dealii9.2.0 installation
