### ISSUE TITLE
CMAKE version insufficient for building Trilinos on CentOS7

### ISSUE THREAD

**Issue by ohcfe** [dealii/candi#154]
On CentOS the `cmake` package installs version 2.8.12.2, and the cmake3 package installs version 3.17.3 to `/usr/bin/cmake3` which leads to Trilinos complaining that the installed version of cmake is insufficient.

I worked around the problem by un-commenting the following line in `candi.cfg`:
```bash
PACKAGES="${PACKAGES} once:cmake"
```

**Comment by koecher** [comment]
Dear @ohcfe 
yes you are right, we should add this cmake package by default on centos7, are you working on centos8?
Your workaround is exactly what one should do.
Best
  Uwe

**Comment by ohcfe** [comment]
this system, unfortunately, needs to be compatible with ABAQUS, so I'm stuck on CentOS 7. And even more unfortunately CentOS 8 will not be a thing passed 2021:
https://itsfoss.com/centos-stream-fiasco/

on my workstation I run arch and have no problems with super old versions of stuff.

**Comment by ohcfe** [comment]
> Dear @ohcfe
> yes you are right, we should add this cmake package by default on centos7, are you working on centos8?
> Your workaround is exactly what one should do.
> Best
> Uwe

I'm working on CentOS 7, I played around to moving to CentOS 8, however there were too many painful things in the CentOS 7 -> CentOS 8 transition to do with enterprise software I have to use to let me make the switch.

On systems that don't need old libs for enterprise software I tend to run arch.
