### ISSUE TITLE
candi 9.3 release

### ISSUE THREAD

**Issue by tjhei** [dealii/candi#201]
This is to be done for 9.3:
- [x] create branch: https://github.com/dealii/candi/tree/dealii-9.3 
- [x] fix OSX gcc9 link failure in step-66 (deal.II bug? https://github.com/dealii/dealii/issues/12490)
- [x] some more testing
- [x] make 9.3 the default branch

**Comment by tjhei** [comment]
I just made 9.3 the default branch. We should probably take over some (all?) of the more recent changes.

Anything else that needs to be done @koecher ?

**Comment by koecher** [comment]
I think we can take over all recent changes to 9.3.

**Comment by tjhei** [comment]
I just did exactly that!
