### ISSUE TITLE
Git tag vs VERSION

### ISSUE THREAD

**Issue by gfcas** [dealii/candi#234]
I observed that sometimes the git tag or branch we want to download has a different name, e.g., vX.Y.Z or X.Y.Z, or even gmsh_X_Y_Z. Therefore I would like to ask you, what about adding a variable ``GITTAG`` or something else, that indicates the branch or tag we want down get from a git repo. Currently the ``VERSION`` variable is used therefore.

**Comment by koecher** [comment]
I know, but let it keep it as simple as is it now.
In general it isn't very unified how we create the `NAME`, `EXTRACTSTO`, `VERSION` etc.

**Comment by gfcas** [comment]
OK, yes maybe it depends also on the different libraries. Let's close it.

**Comment by koecher** [comment]
this is something for a strategic meeting in the future. nothing urgent. Thanks for reporting and closing
