### ISSUE TITLE
cmake 3.20 MPI compiler selection broken

### ISSUE THREAD

**Issue by tjhei** [dealii/candi#244]
It seems #207 is required when using cmake 3.20 and not only for deal.II but also Trilinos, so we will need to do additional work. Otherwise I can not pick a different CXX compiler.

**Comment by koecher** [comment]
okay, I take a deeper look on that topic using virtual machines. I can't believe that we broke everything and try to find a solution.

**Comment by tjhei** [comment]
Has nothing to do with us breaking things: cmake 3.20 (at least, maybe earlier) requires setting the compiler and the MPI wrapper.

**Comment by tjhei** [comment]
I will prep something once the ASPECT hackathon is over in a week.

**Comment by tjhei** [comment]
I played with this some more and I think I made a mistake: it turns out ``gcc`` is a symlink to ``clang`` on OSX. I think this issue can be closed.

**Comment by koecher** [comment]
resolved
