### ISSUE TITLE
Use ninja instead of make

### ISSUE THREAD

**Issue by bangerth** [dealii/candi#253]
#252 reminds me that since we're already downloading all sorts of stuff in candi, we might as well download 'ninja' and use that instead of 'make' whenever we build something via 'cmake'. Ninja is so much faster on large build projects that that might be worth the slight complication due to downloading and building it.

**Comment by gfcas** [comment]
@bangerth Interesting, only heard about ninja but never used it. I tried a quick and dirty solution to build dealii with ninja for a wall time comparison. However, the make version was a bit faster, see https://github.com/gfcas/candi/actions/runs/1182195219. May it depend on the number of available CPUs building the project?

**Comment by tjhei** [comment]
Ninja is a) parallel by default, so you should not specify -j and b) quite a bit faster for incremental builds. There is no big difference when you build from scratch.
Finally, CI with 2 cores is not a situation where I would expect a big difference.
I don't think using ninja is very helpful to be used in candi.

**Comment by gfcas** [comment]
Thanks for your experience. Unfortunately I was only able to test it with the GitHub runners, which have only two cores.
When I think on an installation in parallel it might be a little bit dangerous to build the big packages trilinos/dealii with an unspecified number of cores on a laptop with usual amount of RAM? (My first laptop overheated using 4 cores + 16GB RAM).

**Comment by tjhei** [comment]
Part of the high RAM requirements is trilinos and our current configuration, but yes, I understand your point.
One more reason not to use ninja then.

**Comment by bangerth** [comment]
Fair enough -- let's close it then. I think all of us with bigger machines use ninja primarily because it automatically figures out how many processes to use, and because it is much faster when only a few files have to be compiled. But you're right that neither of this is relevant here.
