### ISSUE TITLE
Installing problem of ver 9.3.1 of DEAL.II 

### ISSUE THREAD

**Issue by sungho91** [dealii/candi#263]
I am trying to install the latest deal.ii.

I activated MKL=on and added proper directories (Fig.2).
However, candi cannot find the directories (Fig.3).

Plus, I inactivated all system dependencies but candi forced to install all packages (Fig.1).

Any comments can be helpful for me.

Best regards

Sungho

Figure 1. a screen capture (Inactivating system dependencies)
![1](https://user-images.githubusercontent.com/40257026/133755924-f2f9e6b4-9dfa-46a1-855b-c1d89e722ed6.png)

Figure 2. a screen capture (Activating MKL)
![2](https://user-images.githubusercontent.com/40257026/133755932-74269e33-8893-4089-ae35-072063f9a07c.png)

Figure 3. a screen capture (candi force to install the system dependencies which I inactivated. Also, candi could not find MKL)
![3](https://user-images.githubusercontent.com/40257026/133755945-a43ef6fc-34ef-4ab3-8605-0205b2243a98.png)

**Comment by koecher** [comment]
do you have a local.cfg in the folder of candi? This would overwrite the configuration of candi.cfg.

What platform (operating system) are you using?

**Comment by koecher** [comment]
candi will not report on MKL settings, those are given internally to the packages. It only reports that the compilers are not set by an export. But the detection of the intel mpi compilers seems correct to me.

**Comment by sungho91** [comment]
> do you have a local.cfg in the folder of candi? This would overwrite the configuration of candi.cfg.
> 
> What platform (operating system) are you using?

The platform is a cluster using CentOS 7. So I appended an argument "--platform=deal.II-toolchain/platforms/supported/linux_cluster.platform".

**Comment by sungho91** [comment]
> candi will not report on MKL settings, those are given internally to the packages. It only reports that the compilers are not set by an export. But the detection of the intel mpi compilers seems correct to me.

I thought the previous candi was showing the relevant path of mkl.
Maybe I remember incorrectly.

**Comment by koecher** [comment]
in the recent versions we show it not globally, but in front of a package installation during the process.

But I'm not sure if we have merged everything from the testing branches, which optimises the blas/lapack (mkl) dirs in the packages.

**Comment by koecher** [comment]
> > do you have a local.cfg in the folder of candi? This would overwrite the configuration of candi.cfg.
> 
> > 
> 
> > What platform (operating system) are you using?
> 
> 
> 
> The platform is a cluster using CentOS 7. So I appended an argument "--platform=deal.II-toolchain/platforms/supported/linux_cluster.platform".
> 
> 
> 
> After I did git candi, I only changed the path of MKL in candi.cfg. 
> 
> So, this is only candi.cfg I have. 

okay, can you check if packages are enabled in the linux_cluster.platform file?

Those will be always active regardless of the candi.cfg file.

**Comment by koecher** [comment]
centos7 should be detected automatically and adds currently cmake by the platform file, so you can use this as well.

The main difference is that you may see different installation note on the first two page outputs of candi.
