### ISSUE TITLE
Issue installing deal ii

### ISSUE THREAD

**Issue by Whatsoever** [dealii/candi#271]
Hi,

I have download candi in order to install deal II.  I am using wsl in windows 11. I am not sure if that is the proper place to ask about my problem, if not please let me know where. I got the following problem:

<img width="657" alt="Unbenannt" src="https://user-images.githubusercontent.com/4172876/147506994-771c5aee-f86f-4035-8ffe-af7283437d36.png">

Do you know what I can try to solve it? 

Thanks

Best regards

**Comment by koecher** [comment]
the cmake app couldn't be found.

Have you done the installation notes from the first page of candi?

**Comment by Whatsoever** [comment]
Thanks Uwe,

Actually, I did not read all the notes, I skipped (unpurposely) the first part, **sorry**.
Although, now I have another problem, if I run the command:

_./candi.sh_

my computer can install deal II, 

<img width="985" alt="Unbenannt2" src="https://user-images.githubusercontent.com/4172876/147592512-2a7ba014-26e0-4eee-b8dd-bd143d8db6d5.png">

but if I run

_./candi.sh -j 16_

I got the following issue:

<img width="594" alt="Unbenannt3" src="https://user-images.githubusercontent.com/4172876/147592602-a91f28b3-8973-44fa-b5a9-2b17f512f408.png">

Is this issue related to the amount of memory?  (From the read me: **Be careful with this option! You need to have enough system memory (e.g. at least 8GB for 2 or more processes).**) If I am not wrong I am supposed to have 32GB.
What should I do? Installed with less processors or maybe I forgot another previous step?


Thanks

**Comment by koecher** [comment]
it's hard to say. Your first picture was a perfect build. Keep care of the after building messages as well. 

The other building was failing for the deal.II lib, if you have missed the installation notes again, try it again with them. 

candi only builds new libraries.

DRAM Memory shouldn't be a problem, but you may try it with less processes. 

It's in you hand now
