### ISSUE TITLE
Problem with scaling

### ISSUE THREAD

**Issue by mostanad** [dealii/candi#274]
Hi there,
I have installed dealii using candi but I have a problem with parallel computing. When I change the number of cores for the step-17 example file, it shows e the following wall time:
**time mpirun -np 1 ./step-17
real 0m17.701s
time mpirun -np 2 ./step-17
real 0m16.507s
time mpirun -np 4 ./step-17
real 0m33.934s**
My operating system is Ubuntu 18.04, Intel® Core™ i7-8700 CPU @ 3.20GHz × 12, and I followed the instructions you provided on github. I have seen an option in dealii cmake which is:
**-DDEAL_II_WITH_MPI=ON**
Is there something about this option for parallel computing? How can we activate it for installation?
Cheers,
Mohammad

**Comment by mostanad** [comment]
I have seen it in the dealii.package:
[-D DEAL_II_WITH_MPI:BOOL=ON](https://github.com/dealii/candi/blob/1b914298fb1c54440e74551b0ee79e8a7051ad06/deal.II-toolchain/packages/dealii.package#L20)
But I don't know why I can't see its effect in my tunning tests.

**Comment by bangerth** [comment]
This isn't a problem with candi, but if anything with deal.II. Please ask on the deal.II mailing list.
