### ISSUE TITLE
Takeover PRs

### ISSUE THREAD

**Issue by gfcas** [dealii/candi#292]
Sorry, I am a bit confused. Are the PR #267 and #289 are already merged into master? For me they seem to be only merged into deali-9.3...

**Comment by koecher** [comment]
@gfcas looks like that they were both merged into the 9.3 branch, not the master

**Comment by koecher** [comment]
i'll wait for the basic tester and merge - I hope commits from both PRs were reviewed

**Comment by gfcas** [comment]
> i'll wait for the basic tester and merge - I hope commits from both PRs were reviewed

I think so @tjhei reviewed them.

**Comment by tjhei** [comment]
I am confused, did you guys not see #290 and #291?

**Comment by koecher** [comment]
@tjhei Oops, no I haven't seen them. Sorry

**Comment by gfcas** [comment]
I am very sorry! I looked through the git log history searching for '267' and '289' in the commit message without finding them...

**Comment by tjhei** [comment]
No worries.
