### ISSUE TITLE
problem of candi installation

### ISSUE THREAD

**Issue by Lydia823** [dealii/candi#305]
Hello,
I have installed candi on my mac M1. However, when I test the example step-32, there are some problems resulting.
After typing "cmake . && make", some of the output are like this,

```
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Autopilot invoked
###
#
#  Project  step-32  set up with  deal.II-9.4.0  found at
#      /Users/cuirh/dealii-candi/deal.II-v9.4.0
#
#  CMAKE_BUILD_TYPE:          Debug
#
#  You can now run
#       $ make                - to compile and link the program
#       $ make run            - to (compile, link and) run the program
#
#       $ make sign           - to sign the executable with the supplied OSX developer key
#
#       $ make debug          - to switch the build type to 'Debug'
#       $ make release        - to switch the build type to 'Release'
#
#       $ make edit_cache     - to change (cached) configuration variables
#                               and rerun the configure and generate phases of CMake
#
#       $ make strip_comments - to strip the source files in this
#                               directory off their comments; this is irreversible
#       $ make clean          - to remove the generated executable as well as
#                               all intermediate compilation files
#       $ make runclean       - to remove all output generated by the program
#       $ make distclean      - to clean the directory from _all_ generated
#                               files (includes clean, runclean and the removal
#                               of the generated build system)
#       $ make info           - to view this message again
#
#  Have a nice day!
#
###
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/cuirh/dealii-candi/deal.II-v9.4.0/examples/step-32
[ 50%] Building CXX object CMakeFiles/step-32.dir/step-32.cc.o
[100%] Linking CXX executable step-32
[100%] Built target step-32
cuirh@crh-mac step-32 % mpirun -n 2 ./step-32
dyld[41081]: Library not loaded: 'libTKBO.11.dylib'
  Referenced from: '/Users/cuirh/dealii-candi/deal.II-v9.4.0/examples/step-32/step-32'
  Reason: tried: '/libTKBO.11.dylib' (no such file), '/Users/cuirh/dealii-candi/parmetis-4.0.3/lib/libTKBO.11.dylib' (no such file), 'libTKBO.11.dylib' (no such file), '/usr/local/lib/libTKBO.11.dylib' (no such file), '/usr/lib/libTKBO.11.dylib' (no such file), '/libTKBO.11.dylib' (no such file), '/Users/cuirh/dealii-candi/parmetis-4.0.3/lib/libTKBO.11.dylib' (no such file), '/Users/cuirh/dealii-candi/deal.II-v9.4.0/examples/step-32/libTKBO.11.dylib' (no such file), '/usr/local/lib/libTKBO.11.dylib' (no such file), '/usr/lib/libTKBO.11.dylib' (no such file)
dyld[41082]: Library not loaded: 'libTKBO.11.dylib'
  Referenced from: '/Users/cuirh/dealii-candi/deal.II-v9.4.0/examples/step-32/step-32'
  Reason: tried: '/libTKBO.11.dylib' (no such file), '/Users/cuirh/dealii-candi/parmetis-4.0.3/lib/libTKBO.11.dylib' (no such file), 'libTKBO.11.dylib' (no such file), '/usr/local/lib/libTKBO.11.dylib' (no such file), '/usr/lib/libTKBO.11.dylib' (no such file), '/libTKBO.11.dylib' (no such file), '/Users/cuirh/dealii-candi/parmetis-4.0.3/lib/libTKBO.11.dylib' (no such file), '/Users/cuirh/dealii-candi/deal.II-v9.4.0/examples/step-32/libTKBO.11.dylib' (no such file), '/usr/local/lib/libTKBO.11.dylib' (no such file), '/usr/lib/libTKBO.11.dylib' (no such file)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node crh-mac exited on signal 6 (Abort trap: 6).
--------------------------------------------------------------------------
cuirh@crh-mac step-32 % ls
CMakeCache.txt		Makefile		step-32.cc		step-32.release
CMakeFiles		cmake_install.cmake	step-32.debug
CMakeLists.txt		step-32			step-32.prm
cuirh@crh-mac step-32 % 
```

Could anyone please tell me what is the reason for this problem? Also, what should I do to resolve this problem, please? 

Thanks a lot.

**Comment by bangerth** [comment]
Do you get the same error with step-1, for example?

The key reason is this line:
```
Library not loaded: 'libTKBO.11.dylib'
```
Apparently, the system does not contain this library. I don't have any idea what it is supposed to do.

**Comment by tjhei** [comment]
This error is from open cascade, which currently does not work correctly on M1. I would suggest you rerun Candi from scratch without open cascade for now.

Also see https://github.com/dealii/dealii/wiki/Apple-ARM-M1-OSX
We should probably make it more obvious somewhere what works and doesn't work on ARM right now. Sorry about that.

**Comment by Lydia823** [comment]
> Do you get the same error with step-1, for example?
> 
> The key reason is this line:
> 
> ```
> Library not loaded: 'libTKBO.11.dylib'
> ```
> 
> Apparently, the system does not contain this library. I don't have any idea what it is supposed to do.

Hi Prof. bangerth, thanks for your reply. According to your suggestion, I have tested the example step-1, and got the same error as that with step-32. Also, I have found the file 'libTKBO.11.dylib' under the library of the oce I setup. The question now is I don't know how to make it be found in the future whenever I run dealii. I am a new hand with the mac OS system.

**Comment by bangerth** [comment]
"start from scratch" = do it again, in a new directory that does not contain any remnants of your previous experiment.

Without cascade: candi is driven by a configuration file in which you can switch dependencies on/off. Switch off the OpenCASCADE or OCC dependency (I don't recall how it is named, but it is one of these two names).

**Comment by Lydia823** [comment]
Thanks for your kind explanation Prof. bangerth. I understand now that I need to reinstall dealii with candi and make specific configuratiion of switching off the OpenCascade. I will try that.

**Comment by tjhei** [comment]
Starting from scratch means deleting the output directory Candi produced (typically deal.ii-candi in your home directory) and running Candi again.
You can specify the packages to install on the command line as shown on the wiki page I linked above or by commenting out lines in the candi.cfg.

**Comment by Lydia823** [comment]
Do you mean that when I reinstall candi I should use the commond line like this, './candi.sh -j 8 --packages="hdf5 p4est trilinos dealii", please? The important point is I should specify the parameter packages rather than with the default value, isn't it? @tjhei  I didn't specify this parameter when I installed candi before.

**Comment by tjhei** [comment]
> Do you mean that when I reinstall candi I should use the commond line like this, './candi.sh -j 8 --packages="hdf5 p4est trilinos dealii", please?

Yes, this is one option. Another one is to en candi.cfg and choosing the packages you want.

I don't know what you are trying to do, so I don't know what packages you need.

**Comment by Lydia823** [comment]
The goal I install candi is to install aspect. So do you know what packages should I need during candi installation, please?  Thanks. @tjhei

**Comment by tjhei** [comment]
Take a look at https://github.com/geodynamics/aspect/wiki/Installation-on-ARM-OSX

**Comment by Lydia823** [comment]
I have reinstalled dealii with candi successfully, thanks a lot. @tjhei  @bangerth
