### ISSUE TITLE
petsc.package native optimisation compilation error

### ISSUE THREAD

**Issue by DanW97** [dealii/candi#306]
Hi,

I was getting an error when compiling petsc 3.16.4 with native optimisations, with the compilation process being upset that 
`user provided flags for language c with coptflags: '-o3 are not correct for the compiler`. I'm using candi to install dealii v9.4.0 on a box running Ubuntu 20.04.

When I removed the single quotes around the compiler flags in `petsc.package` to read
```
if [ ${NATIVE_OPTIMIZATIONS} = ON ]; then
    CONFOPTS="${CONFOPTS} \
      COPTFLAGS=-O3 -march=native -mtune=native \
      CXXOPTFLAGS=-O3 -march=native -mtune=native \
      FOPTFLAGS=-O3 -march=native -mtune=native"
fi
```
instead of
```
if [ ${NATIVE_OPTIMIZATIONS} = ON ]; then
    CONFOPTS="${CONFOPTS} \
      COPTFLAGS='-O3 -march=native -mtune=native' \
      CXXOPTFLAGS='-O3 -march=native -mtune=native' \
      FOPTFLAGS='-O3 -march=native -mtune=native'"
fi
```
then compilation succeeds and deal.ii (and [lethe](https://github.com/lethe-cfd/lethe)) appear to work as intended - so I don't think that I have broken anything. I'm not an expert on compiling large and complex packages so I wasn't sure if I missed something by passing the flags in single quotes rather than containing them in the parent string belonging to `CONFOPTS`.

So, if this was incorrect then I can do a pull request.

Cheers, 
Dan

**Comment by tjhei** [comment]
Sadly, the options are not being picked up correctly this way (only -O3 is applied). I worked around it, though, see #307.
