### ISSUE TITLE
How to use self-build library?

### ISSUE THREAD

**Issue by jochenkamm** [dealii/candi#328]
How can I tell candi to use my self-compiled version of PETSC?

I am having trouble building PETSC (because MUMPS for some reason doesn't seem to work even though it was installed apparently fine...)

```
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-mumps-dir=/home/my_usrname/dealii-candi/mumps-5.4.0.5 did not work
*******************************************************************************

Failure with exit status: 1
Exit message: petsc ./configure failed
```

Having gone into why this didn't work for a while now, I thought it might be easier to just supply my own PETSC, this might be easier to solve. 

System: RHEL8
gcc version 8.5.0 20210514 (Red Hat 8.5.0-16) (GCC)

**Comment by tjhei** [comment]
> my self-compiled version of PETSC?

candi is not meant to work with a combination of self-installed and automatically installed dependencies. You can disable installation of PETSc in candi.cfg. Whether the deal.II installation through candi picks up your installation, I don't know.
You can also always install deal.II yourself if you have dependencies installed (through candi or yourself).

**Comment by jochenkamm** [comment]
Ok, thank you. I got the external PETSC linked by setting environment variables PETSC_ARCH and PETSC_DIR but had to remove SLEPC as well, which probably would have required PETSC.
