### ISSUE TITLE
Issue with checksum in slepc

### ISSUE THREAD

**Issue by rnpratoori** [dealii/candi#348]
Hello team,

I am trying to install deal.ii and I kept running into a checksum issue during slepc installation. I noticed that the checksum for 3.19.0 is same as 3.16.2 which could be leading to this issue. I have downloaded the file and looked up the sha256 checksum for 3.19.0 and it is 724f6610a2e38b1be7586fd494fe350b58f5aee1ca734bd85e783aa9d3daa8de.

Best,
Raghunandan.

**Comment by tjhei** [comment]
Yes, thank you. Fixed in #349
