### ISSUE TITLE
create tarball for opencascade v0.18

### ISSUE THREAD

**Issue by koecher** [dealii/candi#35]
@tjhei may you be so kind and create a tarball for opencascade v0.18.

We have included the version v0.18 for some macOS specific compilation error.

**Comment by tjhei** [comment]
I don't remember why we are not using the official tarballs, do you? I created the 0.18.1 tarball in my github repo (this includes the OSX fix).

**Comment by koecher** [comment]
Thanks.
I really don't know why you have created them in such a way.

**Comment by tjhei** [comment]
okay, the official one also works. ;-)

**Comment by koecher** [comment]
Perfect. I'll merged your PR.
