### ISSUE TITLE
muelu compilation

### ISSUE THREAD

**Issue by ajithperera** [dealii/candi#364]
Hello: I am getting the following error
/home/perera/dealii-candi/tmp/unpack/Trilinos-trilinos-release-14-0-0/packages/muelu/adapters/stratimikos/Thyra_MueLu
PreconditionerFactory_def.hpp(739): error: a type qualifier is not allowed on a nonmember function
    RCP<const ParameterList> MueLuPreconditionerFactory<Scalar,LocalOrdinal,GlobalOrdinal,Node>::getParameterList() c
onst {
                                                                                                                    ^

compilation aborted for /home/perera/dealii-candi/tmp/unpack/Trilinos-trilinos-release-14-0-0/packages/muelu/adapters
/stratimikos/Stratimikos_MueLuHelpers.cpp (code 4)

I have modules intel/2020.0.166 and  openmpi/4.1.5  loaded, Any advice on how to get around this is greatly appreciated,

**Comment by bangerth** [comment]
@ajithperera This is at its core a problem with Trilinos: They have to fix the code or work around compiler bugs. Please report the issue with the Trilinos folks.
