### ISSUE TITLE
Want to turn into C99 model in building p4est

### ISSUE THREAD

**Issue by Li2PbO3** [dealii/candi#366]
Error occurred while building p4est.
(The language of my operating system is ZH-CN, so the error msg is in Chinese... I'd better shows the original text and translate for you to prevent my translating mistakes. Sorry to bother you)

/public/home/zhiqianli/dealii-candi/tmp/unpack/p4est-2.3.2/src/p8est_connectivity.c: 在函数‘p8est_connectivity_new_torus’中 ( inside the function 'p8est_connectivity_new_torus' ) :

/public/home/zhiqianli/dealii-candi/tmp/unpack/p4est-2.3.2/src/p8est_connectivity.c:930:5: 错误：只允许在 C99 模式下使用‘for’循环初始化声明 ( ERROR: 'for' loop initialization declaration is only allowed in C99 mode )
     for (int i=0; i<num_vertices*3; ++i)
     ^
/public/home/zhiqianli/dealii-candi/tmp/unpack/p4est-2.3.2/src/p8est_connectivity.c:930:5: 附注：使用 -std=c99 或 -std=gnu99 来编译您的代码 ( PS: Use -std=c99 or -std=gnu99 to compile your code )
/public/home/zhiqianli/dealii-candi/tmp/unpack/p4est-2.3.2/src/p8est_connectivity.c:947:5: 错误：只允许在 C99 模式下使用‘for’循环初始化声明 ( ERROR: 'for' loop initialization declaration is only allowed in C99 mode )
     for (int iSegment=0; iSegment<nSegments; ++iSegment)
     ^
......
<more ERRORs about 'for' loop variable initialization declaration>
......

make[2]: *** [src/libp4est_la-p8est_connectivity.lo] 错误 ( ERROR )  1
make[1]: *** [all-recursive] 错误 ( ERROR )  1
make: *** [all] 错误 ( ERROR )  2
Error: Error in make p4est

I've load 'mpi/intelmpi/5.1.3.210' as the compiler. The gcc version is 4.8.5 (such an elder...). It's not that hard for me to realize that I should change the compiler into a new one (I can't for I'm not the administrator of the server), or turn into C99 model as the msg told above.

However I have no idea about how to add the parameter '-std=c99' or '-std=gnu99'. (Or there might be some other ways to solve it?) So I need some help. Many thanks!

**Comment by tjhei** [comment]
> I've load 'mpi/intelmpi/5.1.3.210' as the compiler. The gcc version is 4.8.5 (su

please use newer compilers.

**Comment by bangerth** [comment]
You might also be able to get C99 support if you do something along the lines of
```
export CFLAGS="-std=c99"
```
