### ISSUE TITLE
Trilinos: Symbol(s) not found for architecture arm64 during Linking CXX shared library libteko.dylib

### ISSUE THREAD

**Issue by cgw0814** [dealii/candi#372]
I'm using Apple-Silicon M2 to install tilinos

When I build trilinos-release-15.0.0 with setting from [https://github.com/dealii/candi/blob/master/deal.II-toolchain/packages/trilinos.package](url)

`cmake \         
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
  -D TPL_ENABLE_TBB:BOOL=OFF \
  -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=OFF \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=ON \
  -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack2:BOOL=OFF \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:BOOL=ON \
  -D Trilinos_ENABLE_Sacado:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D   Teuchos_ENABLE_FLOAT:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
  -D Trilinos_ENABLE_NOX:BOOL=ON \
  -D Trilinos_ENABLE_ROL:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
  -D TPL_ENABLE_Boost:BOOL=OFF \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Amesos2:BOOL=ON \
  -D TPL_ENABLE_Matio=OFF \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
  -D BUILD_SHARED_LIBS:BOOL=ON \`

and then make install

the errors appear during Linking CXX shared library libteko.dylib

`[ 83%] Linking CXX shared library libteko.dylib
Undefined symbols for architecture arm64:
  "__ZN11Stratimikos26LinearSolverBuilderHelpers17existingNameIndexEN7Teuchos9ArrayViewINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKS8_", referenced from:
      __ZNK11Stratimikos19LinearSolverBuilderIdE34getAndAssertExistingFactoryNameIdxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos9ArrayViewIS7_EES9_.isra.0 in Teko_InvLSCStrategy.cpp.o
      __ZNK11Stratimikos19LinearSolverBuilderIdE34getAndAssertExistingFactoryNameIdxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos9ArrayViewIS7_EES9_.isra.0 in Teko_InvModALStrategy.cpp.o
      __ZNK11Stratimikos19LinearSolverBuilderIdE34getAndAssertExistingFactoryNameIdxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos9ArrayViewIS7_EES9_.isra.0 in Teko_LSCPreconditionerFactory.cpp.o
      __ZNK11Stratimikos19LinearSolverBuilderIdE34getAndAssertExistingFactoryNameIdxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos9ArrayViewIS7_EES9_.isra.0 in Teko_LSCSIMPLECStrategy.cpp.o
      __ZNK11Stratimikos19LinearSolverBuilderIdE34getAndAssertExistingFactoryNameIdxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos9ArrayViewIS7_EES9_.isra.0 in Teko_ModALPreconditionerFactory.cpp.o
      __ZNK11Stratimikos19LinearSolverBuilderIdE34getAndAssertExistingFactoryNameIdxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos9ArrayViewIS7_EES9_.isra.0 in Teko_PCDStrategy.cpp.o
      __ZNK11Stratimikos19LinearSolverBuilderIdE34getAndAssertExistingFactoryNameIdxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos9ArrayViewIS7_EES9_.isra.0 in Teko_PresLaplaceLSCStrategy.cpp.o
      ...
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[2]: *** [packages/teko/src/libteko.15.1.dylib] Error 1
make[1]: *** [packages/teko/src/CMakeFiles/teko.dir/all] Error 2
make: *** [all] Error 2`

How could I solve this problem?

**Comment by bobmyhill** [comment]
As far as I can see in https://github.com/dealii/candi/blob/master/deal.II-toolchain/packages/trilinos.package, and https://dealii.org/developer/external-libs/trilinos.html, Trilinos 15.0.0 is not yet tested with deal.II. 

Is there a reason you need the latest release of Trilinos?

**Comment by tjhei** [comment]
This should be fixed with #350, at least I can compile on M1 without issues.
