### ISSUE TITLE
Typo in candi.sh script for the dependencies

### ISSUE THREAD

**Issue by curtcorum** [dealii/candi#52]
Typo in candi.sh script for the dependencies:

sudo apt-get install build-essential wget automake autoconf gfortran \
 openmpi-bin openmpi-common libopenmpi-dev cmake subversion \
 git libblas-dev liblapack-dev libblas3gf liblapack3gf \
 libsuitesparse-dev libtool libboost-all-dev \
 splint tcl tcl-dev environment-modulesqt4-dev-tools

Should be:
... environment-modules qt4-dev-tools

**Comment by bangerth** [comment]
@curtcorum - since you already have the solution ready and also found the correct github location, would you want to create a pull request with a patch and make this your first contribution to deal. II? We'd love to count you among those who have contributed!

**Comment by curtcorum** [comment]
@bangerth - Sure, happy to contribute. Just getting started and not sure exactly how I will be using deal.ii but likely some EM simulations.

**Comment by bangerth** [comment]
Great! Let us know if you need help with creating a pull request to add the missing space in candi!
