### ISSUE TITLE
Failure when building opencascade on Ubuntu 17.10 due to missing "xlocale.h"

### ISSUE THREAD

**Issue by LucasCampos** [dealii/candi#56]
When compiling the OCE version 0.18.1, the build fails due to missing "xlocale.h".

**Comment by LucasCampos** [comment]
I could solve the issue by setting DEVELOPER_MODE=ON on candi.cfg, manually applying the fix mentioned in tpaviot/oce#675 andtelling candi to build/install only opencascade using 

```
./candi.sh --packages="opencascade"
```

Then, I set developer mode off and let candi deal with the other packages normally, i.e.,

```
./candi.sh
```

**Comment by koecher** [comment]
thanks for reporting. There is a new minor version 0.18.2, is the fix included in this version?

**Comment by LucasCampos** [comment]
No, it does not. As a matter of fact, they did not apply the patch to HEAD
yet.
