### ISSUE TITLE
suggestion: provide blas+lapack

### ISSUE THREAD

**Issue by tjhei** [dealii/candi#94]
Some clusters do not have a working blas+lapack. Maybe we can write an (optional) package that uses gotoblas or atlas to provide these? Requires testing it for Trilinos and deal.II of course.

Requested on the ASPECT mailing list.

**Comment by bangerth** [comment]
The cluster folks will not be happy about that. They like to have their optimized blas and lapack packages...

But we don't do much blas anyway, so the performance impact is likely small.

**Comment by tjhei** [comment]
> The cluster folks will not be happy about that. They like to have their optimized blas and lapack packages...

Except when they don't. My suggestion would be to not install it by default of course.

> But we don't do much blas anyway, so the performance impact is likely small.

I am not sure if ML uses blas/lapack.
